export const ADD_RECIPE_START = 'ADD_RECIPE_START';
export const ADD_RECIPE_CANCEL = 'ADD_RECIPE_CANCEL';

export const ADD_INGREDIENT_START = 'ADD_INGREDIENT_START';
export const ADD_INGREDIENT_FINISHED = 'ADD_INGREDIENT_FINISHED';

export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILED = 'FETCH_RECIPE_FAILED';