export const ADD_RECIPE_START = 'ADD_RECIPE_START';
export const ADD_RECIPE_CANCEL = 'ADD_RECIPE_CANCEL';

export const REMOVE_RECIPE_START = 'REMOVE_RECIPE_START';
export const REMOVE_RECIPE_CANCEL = 'REMOVE_RECIPE_CANCEL';

export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILED = 'FETCH_RECIPE_FAILED';